"""init

Revision ID: df334710c131
Revises: 
Create Date: 2026-06-07 16:41:21.848091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'df334710c131'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=255), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=True)
    op.create_table('cursos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('avulso', 'premium', name='tipocurso'), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('validade_dias', sa.Integer(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('destaque', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_slug'), 'cursos', ['slug'], unique=True)
    op.create_table('estoque_carros',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modelo', sa.String(length=160), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'reservado', 'vendido', name='statuscarro'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=160), nullable=False),
    sa.Column('telefone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tipo_servico', sa.String(length=80), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('origem', sa.String(length=80), nullable=True),
    sa.Column('status', sa.Enum('novo', 'contatado', 'agendado', 'concluido', 'perdido', name='statuslead'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=True),
    sa.Column('nome_evento', sa.String(length=120), nullable=False),
    sa.Column('sessao_id', sa.String(length=80), nullable=True),
    sa.Column('propriedades', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_nome_evento'), 'eventos', ['nome_evento'], unique=False)
    op.create_index(op.f('ix_eventos_sessao_id'), 'eventos', ['sessao_id'], unique=False)
    op.create_table('modulos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=True),
    sa.Column('gateway', sa.String(length=40), nullable=False),
    sa.Column('gateway_transaction_id', sa.String(length=120), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'recusado', 'estornado', name='statuspagamento'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pagamentos_gateway_transaction_id'), 'pagamentos', ['gateway_transaction_id'], unique=True)
    op.create_table('aulas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modulo_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('panda_video_id', sa.String(length=120), nullable=True),
    sa.Column('duracao_segundos', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriculas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('pagamento_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'expirado', 'bloqueado', name='statusmatricula'), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.ForeignKeyConstraint(['pagamento_id'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aluno_id', 'curso_id', name='uq_aluno_curso')
    )
    op.create_table('certificados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula_id', sa.UUID(), nullable=False),
    sa.Column('codigo_verificacao', sa.String(length=40), nullable=False),
    sa.Column('emitido_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id')
    )
    op.create_index(op.f('ix_certificados_codigo_verificacao'), 'certificados', ['codigo_verificacao'], unique=True)
    op.create_table('materiais_apoio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('url_pdf', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aluno_id', sa.UUID(), nullable=False),
    sa.Column('matricula_id', sa.UUID(), nullable=True),
    sa.Column('canal', sa.Enum('email', 'whatsapp', name='canalnotificacao'), nullable=False),
    sa.Column('tipo', sa.Enum('vigencia_proxima', 'vigencia_expirada', 'promo_renovacao', name='tiponotificacao'), nullable=False),
    sa.Column('marco', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'enviada', 'falhou', name='statusnotificacao'), nullable=False),
    sa.Column('provedor_msg_id', sa.String(length=120), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enviada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id', 'tipo', 'canal', 'marco', name='uq_notificacao_marco')
    )
    op.create_table('progresso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('matricula_id', sa.UUID(), nullable=False),
    sa.Column('aula_id', sa.UUID(), nullable=False),
    sa.Column('concluida', sa.Boolean(), nullable=False),
    sa.Column('percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.ForeignKeyConstraint(['matricula_id'], ['matriculas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula_id', 'aula_id', name='uq_matricula_aula')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progresso')
    op.drop_table('notificacoes')
    op.drop_table('materiais_apoio')
    op.drop_index(op.f('ix_certificados_codigo_verificacao'), table_name='certificados')
    op.drop_table('certificados')
    op.drop_table('matriculas')
    op.drop_table('aulas')
    op.drop_index(op.f('ix_pagamentos_gateway_transaction_id'), table_name='pagamentos')
    op.drop_table('pagamentos')
    op.drop_table('modulos')
    op.drop_index(op.f('ix_eventos_sessao_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_nome_evento'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_table('leads')
    op.drop_table('estoque_carros')
    op.drop_index(op.f('ix_cursos_slug'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
